services:
  postgres:
    image: postgres:14
    container_name: psql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: users
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: